### ISSUE TITLE
resubscribe should compare states before updating to avoid re-rendering

### ISSUE THREAD

**Issue by grahamlyus** [raisemarketplace/ground-control#15]
First off, this looks like a great library, thanks for putting it out there!

I noticed in one of my components, the `render` function was being called every second (because I was logging the props). I traced it back here: [redux-devtools-log-monitor](https://github.com/gaearon/redux-devtools-log-monitor/blob/e8924b12400d4fd94a5e3bad33b4abe030a07aea/src/LogMonitor.js#L104).

I noticed [Redux's `connect`](https://github.com/reactjs/react-redux/commit/61c9c35d626c5e167086ce329ed1e63459671734) checks if the state has changed before calling `setState`, but the [`resubscribe`](https://github.com/raisemarketplace/ground-control/blob/master/modules/GroundControl.js#L125) function in `GroundControl` does not. 

I monkey-patched it in my project to compare previous and next state to test it out and could provide a pull request if you like:

```
GroundControl.prototype.resubscribe = function () {
  var _this3 = this;

  var store = this.props.store;

  return store.subscribe(function () {
    var prevStoreState = _this3.state.storeState;
    var storeState = store.getState();

    if (prevStoreState !== storeState) {
      _this3.setState({
        storeState: store.getState()
      });
    }
  });
}
```

Is this related to #14 ?

**Comment by ndreckshage** [comment]
Hey @grahamlyus thanks for report! I think redux-devtools-log-monitor might be triggering actions on interval etc. But either way perf stuff similar to connect should be added. Or I should just hook into react-redux itself. Will take a more in depth look this weekend and see if I can improve.

**Comment by grahamlyus** [comment]
Ok, great. BTW its obviously a 1 line compare, as the monkey patch was ES5 as I doubted ES2015 could patch ES2015 transpiled to ES5 ;)

**Comment by ndreckshage** [comment]
Wrapped in connect for now, should solve I believe. Could remove in future for simpler solution like you posted above if desired
