### ISSUE TITLE
combine ground-control with other state?

### ISSUE THREAD

**Issue by mrtnbroder** [raisemarketplace/ground-control#17]
Somehow I am unable to get this working. I have some shared state that I don't want within ground-control, but living beside it.

```
{
  ground-control: { child: ..., meta: ..., self: ...},
  database: { ... }
}
```

I am unable to compose this. As if ground-control removes everything else and just allows state within itself. How do I combine ground-control with other state?

**Comment by mrtnbroder** [comment]
After hours of searching I figured it out:

```
function renderHtml(nextProps, store, initialData) {
    const provider = (
      <GroundControl
        initialData={initialData}
        reducers={rootReducers}
        store={store}
        {...nextProps}
        />
    )
    const content = renderToString(provider)

    return Html.renderToStaticMarkup({ content, initialData })
  }
```

`reducers={rootReducers}`

But now initalData doesn't hold the initalState. How do I get it in there? Just merge it together? Shouldn't this be handled by ground-control?

**Comment by ndreckshage** [comment]
Hey @mrtnbroder -- sorry I missed this, just seeing it now.

I believe you would just make your initial state follow your reducer structure. `{ groundcontrol: { }, database: { } }`

Then everything under groundcontrol will be handled by the framework, everything outside of it will be handled outside.

Nick
