### ISSUE TITLE
Render error handling

### ISSUE THREAD

**Issue by nihark** [raisemarketplace/ground-control#2]
After creating a basic universal app, I noticed - if there is any error in a component the app doesn't throw an error, instead the page response/rendering doesn't complete.

Consider the AsyncComponent from the tutorial for example

``` JavaScript
export const component = React.createClass({
  render() {
    const items = this.props.loading ? ['x', 'y', 'z'] : this.props.data.items;
...
```

and a typo like one below

``` JavaScript
    const items = this.props.loading ? ['x', 'y', 'z'] : this.props.items;
```

**Comment by ndreckshage** [comment]
Thanks @nihark - wouldn't this also be an issue without this plugin? Universal rendering with only React-Router?
