### ISSUE TITLE
Custom combineReducers/replaceStore

### ISSUE THREAD

**Issue by ndreckshage** [raisemarketplace/ground-control#6]
So that awesome libraries like https://github.com/raisemarketplace/redux-loop work!

**Comment by ndreckshage** [comment]
done

**Comment by jgoux** [comment]
Hello,
could you give an example about how to use redux-loop with ground-control ?

I made all my "pages" based on redux-loop (and the elm architecture), and I'd like to add the routing part now.

I tried ground-control, but I ended up with nested `{ model, effect }` objects, so I assume I didn't wire the things correctly. ^^'

**EDIT** : 

After seeing the examples, I saw the `combineReducers` option on `GroundControl` ! :+1: 

I'll open another issue for my next case. :p
